#import "./UserHeadCourseFields.gql"
#import "./CourseOrderFields.gql"
#import "./CourseContentFields.gql"

fragment CourseFields on CourseEntity {
  id
  createAt
  updateAt
  name
  price
  prePrice
  hash_key
  keywords
  head {
    ...UserHeadCourseFields
  }
  CourseOrder {
    ...CourseOrderFields
  }
  CourseContent {
    ...CourseContentFields
  }
}
